version: "3.8"

services:
  sb-app:
    build: .
    container_name: "CommercePetUsuario-app"
    ports:
      - "8086:8086"
    networks:
      - app_network

  mysql_usuario:
    image: mysql:8.0.30
    container_name: mysql_usuarioBD
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: UsuarioBD
    ports:
      - "3310:3306"
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
