version: "3.8"
services:
  sb-app:
    build: .
    container_name: "CommercePetProduto-app"
    ports:
      - 8083:8083
    networks:
      - app_network

  mysql_Produto:
    image: mysql:8.0.30
    container_name: mysql_ProdutoBD
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ProdutoBD
    ports:
      - "3309:3306"
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - app_network

networks:
  app_network:
    driver: bridge